services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    build:
      context: ./php
      args:
        - PHP_VERSION
        - UID
        - GID
    volumes:
      - ..:/app
      - /app/.git # exclude .git
    working_dir: /app
    environment:
      - COMPOSER_HOME=/tmp/composer
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MARIADB_HOST
      - MARIADB_PORT
      - MARIADB_USER
      - MARIADB_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password

  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: password

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
